#!/bin/sh
set -eu
APPDIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
export APPDIR
export LD_LIBRARY_PATH="$APPDIR/usr/lib:$APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="$APPDIR/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
export GSETTINGS_SCHEMA_DIR="$APPDIR/usr/share/glib-2.0/schemas"
export GIO_MODULE_DIR="$APPDIR/usr/lib/gio/modules"
export GDK_PIXBUF_MODULEDIR="$APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders"
export GDK_PIXBUF_MODULE_FILE="$APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache"
export FONTCONFIG_PATH="$APPDIR/etc/fonts"
export FONTCONFIG_FILE="$APPDIR/etc/fonts/fonts.conf"
# Ubuntu GTK searches its compiled multiarch libdir; Arch keeps GTK4 IM modules here.
if [ -d /usr/lib/gtk-4.0 ]; then
    export GTK_PATH="${GTK_PATH:+$GTK_PATH:}/usr/lib/gtk-4.0"
fi
exec "$APPDIR/usr/bin/agnam" "$@"
